### ISSUE TITLE
jsctl inconsistent config storage location

### ISSUE THREAD

**Issue by amcginlay** [jetstack/jsctl#52]
Locations where the jsctl auth token is stored as follows:
Linux: ~/.config/jsctl/token.json
MacOS: ~/Library/Application Support/jsctl/token.json

The CLI tools I use most frequently (e.g. aws and kubectl) have consistent config locations across different OS's.
Unless there's a good reason for this unusual discrepancy, may I suggest we standardise on the Linux location (i.e. ~/.config/jsctl/) ?

**Comment by charlieegan3** [comment]
Currently, we use the [go function from the os package in the standard library](https://pkg.go.dev/os#UserConfigDir) to determine where the configuration is stored.

```go
// UserConfigDir returns the default root directory to use for user-specific
// configuration data. Users should create their own application-specific
// subdirectory within this one and use that.
//
// On Unix systems, it returns $XDG_CONFIG_HOME as specified by
// https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html if
// non-empty, else $HOME/.config.
// On Darwin, it returns $HOME/Library/Application Support.
// On Windows, it returns %AppData%.
// On Plan 9, it returns $home/lib.
//
// If the location cannot be determined (for example, $HOME is not defined),
// then it will return an error.
func UserConfigDir() (string, error) {
	var dir string

	switch runtime.GOOS {
	case "windows":
		dir = Getenv("AppData")
		if dir == "" {
			return "", errors.New("%AppData% is not defined")
		}

	case "darwin", "ios":
		dir = Getenv("HOME")
		if dir == "" {
			return "", errors.New("$HOME is not defined")
		}
		dir += "/Library/Application Support"

	case "plan9":
		dir = Getenv("home")
		if dir == "" {
			return "", errors.New("$home is not defined")
		}
		dir += "/lib"

	default: // Unix
		dir = Getenv("XDG_CONFIG_HOME")
		if dir == "" {
			dir = Getenv("HOME")
			if dir == "" {
				return "", errors.New("neither $XDG_CONFIG_HOME nor $HOME are defined")
			}
			dir += "/.config"
		}
	}

	return dir, nil
}
```

I think this makes sense for a few reasons:

* This is idiomatic for each platform we run on
* Users don't need to edit the files themselves as we have commands to set config - so where config is stored shouldn't matter too much. Ideally they won't need to edit the files at all.
* We create less mess in the user's home directory
* It handles windows for us

However, I can see that it's different from what some other CLIs do.

> may I suggest we standardise on the Linux location

Do we risk making jsctl the "unusual discrepancy" on non li/unix platforms with this approach?

**Comment by amcginlay** [comment]
Using `kubectl` as a guide, it's config location is consistent across all OS's that I'm aware of.
I'm not even against it being `~/.jsctl/token.json` it just ought to be consistent IMO.

**Comment by charlieegan3** [comment]
On windows it's at `%USERPROFILE%/.kube`, so it's not always the same as ~ doesn't resolve to %USERPROFILE% in cmd.exe as I understand it.

Right now, we have Go doing the logic of where to put this file based on the operating system. I think that is a valuable feature because we can lean on jsctl to abstract operating system differences. E.g. when https://github.com/jetstack/jsctl/pull/47 merges, we'll have `jsctl config show` which will show the path to the config - regardless of the operating system.

As I see it, we have three options:

### A

Do nothing.

Pros:

* No migration of config needed

Cons:
* Mac users are confused by paths in `~/Library/Application Support`

### B

Make the Mac path `~/.config/jsctl`

Pros:
* No confused Mac users

Cons:
* we have to build jsctl logic to move config for users who have config in `Application Support`
* `~/.config` is an XDG_CONFIG_HOME standard so we divert from the OS standard for Mac users.

### C

We use the same system as Kubectl (~/.jsctl and %USERPROFILE%/.jsctl)

Pros:

* familiar to kubectl users
* No confused Mac users

Cons:

* We have to write migration logic for all platforms
* We don't use any operating system standards on any platform
* We pollute user home directories
* We still need to lean on jsctl to show users where their config is with `jsctl config show` since it won't be in the same place on all three systems (%USERPROFILE% vs ~).


---

It's my preference to use jsctl commands to read from and modify config wherever possible. When users do need to see the state of their config, I'd like it to be a jsctl command that shows them where it is. This is important to me so that once the user has installed the CLI, the differences in the documentation of the tool are kept to a minimum.

https://github.com/jetstack/jsctl/issues/51 is a good example of the cross platform documentation foot guns I'd like to avoid 😞

**Comment by achuchev** [comment]
I second @amcginlay 's request. Option C is common and less confusing. In addition to kubectl, AWS CLI, and GCP CLI are using the same pattern. Typically `~/.config/my-app` on macOS/Linux and `%APPDATA%\my-app` on Windows. I personally prefer `~/.my-app` instead of `~/.config/my-app`, but it against the 

https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html
https://cloud.google.com/sdk/docs/configurations

**Comment by charlieegan3** [comment]
OK fair enough. I think we can move forward with option three in that case. Since it's a bit of work, it might me a while to get around to it.

On windows, neither aws nor kubectl seem to use AppData, but rather `C:\Users\USERNAME\.thing`. Do we want to use AppData on windows?

**Comment by amcginlay** [comment]
I think we will see a rise in the use of `/.config/` as it limits config clutter.

So, if I'm not being too particular, perhaps **Option D** is:
```
<HOWEVER_HOME_DIRECTORY_IS_DETERMINIED>/.config/configfile
```

I'm not 100% sure what WIndows users would expect re `AppData` these days, but so many are using WSL that I doubt they'll be too concerned with the mainstream standards.

And, just for fun ...
https://i.redd.it/l4bu591x5syy.jpg

**Comment by charlieegan3** [comment]
🙂☁️

I can ask around about the windows configuration path.

**Comment by charlieegan3** [comment]
I had some input that USERPROFILE is expected more on Windows - so I'll go with that.

I'm going to start working on this, but it's likely to be pushed down the list later today as we plan Q4.

**Comment by charlieegan3** [comment]
I have implemented the migration and change of default in https://github.com/jetstack/jsctl/pull/47 in https://github.com/jetstack/jsctl/pull/47/commits/c897bbe6407d18118bf47e8d3c4e002cff60c25c

**Comment by charlieegan3** [comment]
#47 has been merged, the default path is now based on the [os.UserHomeDir](https://cs.opensource.google/go/go/+/refs/tags/go1.19.2:src/os/file.go;l=499) + /.jsctl/*.


https://github.com/jetstack/jsctl/blob/bbad8ede5919e5824583661473ca5d7b86e1edc8/internal/config/config.go#L32

**Comment by charlieegan3** [comment]
Please open a new issue if you run into issues with this or the migration.
